kind: pipeline
name: build

platform:
  os: windows
  arch: amd64
  version: 1803

steps:
- name: build
  image: node:4
  pull: never
  commands:
  - cd g:/
  - npm install
  - echo "done"
  #- dotnet build Project/Project.csproj
