kind: pipeline
name: build

platform:
  os: windows
  arch: amd64
  version: 1803

steps:
- name: build
  image: node:4
  pull: never
  commands:
  - cd g:\
  - npm --prefix ./ControlCenter/Content install ./ControlCenter/Content
  #- dotnet build Project/Project.csproj
