kind: pipeline
name: build

platform:
  os: windows
  arch: amd64
  version: 1803

steps:
- name: build
  image: node:4
  pull: never
  commands:
  - npm --prefix g:/ControlCenter/Content install g:/ControlCenter/Content
  #- dotnet build Project/Project.csproj
